add doc for update email & document number
koyweforest/docs pull request #27
Opened 2024-02-15 16:41 UTC by NicoWeisheim

2024-02-15 16:57 UTC, gjacuna requested changes

2024-02-15 16:57 UTC, gjacuna commented on documentacion/documentacion-api/api-graphql.mdx
> +updateDocumentNumberCallback
Este lenguaje está raro. metaAccount es una entidad interna (de cara a clientes es client) y no entiendo bien a Qué se refiere. ¿vamos a mandarle un evento a esa url?

2024-03-06 18:08 UTC, juanarfuch approved these changes

2024-03-06 18:28 UTC, fabroAldo approved these changes

2024-03-06 19:51 UTC, gjacuna requested changes

2024-03-06 19:51 UTC, gjacuna commented on english/documentation/api-documentation/graphql-api.mdx
> +validation on metamap for missmatching personal data. The results of the asynchronous validation will be sent to the configured callback.
Tiene algunas faltas gramaticales. ¿Le puedes pedir a GPT que las corrija por fa?

2024-03-06 21:02 UTC, mbustosp approved these changes

2024-03-06 21:23 UTC, gjacuna approved these changes

2024-03-06 21:39 UTC, merged